### ISSUE TITLE
Update DLICV package to NNUnetV2 and Python 3.12 with refined I/O

### ISSUE THREAD

**Issue by gurayerus** [georgeaidinis/DLICV#2]
NNUnet version will be updated;
model training is completed and validations are done;
MONAI dependencies for calling the testing will be removed
The IO for testing will be made simple and clear (e.g. apply --indir --outdir etc)

**Comment by spirosmaggioros** [comment]
Latest commit updated DLICV on PyPI and uses only -i and -o as arguments. This is closed!
